[package]
name = "pkg-diff"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.4.3"
tokio = { version = "1.15.0", features = ["full"] }
minijinja = { version = "0.12.0", features = ["source"] }
lazy_static = "1.4.0"
